// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:scbs/data/models/customer.dart';
import 'package:scbs/data/models/order.dart';
import 'package:scbs/data/models/order_item.dart';
import 'package:scbs/data/models/product.dart';
import 'package:scbs/data/models/settings.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CustomerAdapter());
    registerAdapter(OrderAdapter());
    registerAdapter(OrderItemAdapter());
    registerAdapter(ProductAdapter());
    registerAdapter(SettingsAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CustomerAdapter());
    registerAdapter(OrderAdapter());
    registerAdapter(OrderItemAdapter());
    registerAdapter(ProductAdapter());
    registerAdapter(SettingsAdapter());
  }
}
